### ISSUE TITLE
Banner enhancement

### ISSUE THREAD

**Issue by VegasHC** [VegasHC/eileen200#14]
![Example](https://user-images.githubusercontent.com/98860212/207956591-5907d85d-54c0-4874-bf86-06a8ea884259.png)
![Example2](https://user-images.githubusercontent.com/98860212/207956614-b6f6fb2d-37f0-4fd4-bcea-8d87133d51f9.png)

Hi Erin,

We want to be able to add link an imagine or clickable design on the top right of the banner where it will go to a new page. 

On the new page as shown in the Example drawing. We would like it have a similar view as what was drawn. We would like to have a link or hyperlink to our facebook group page where it shows "stay connected" in the picture I included and on the left of that we will have our logo. Also another form to be added for people to submit their information. If we need to jump on a call to go over it better I am all for it.

**Comment by edalzell** [comment]
I'll review this next week.

**Comment by edalzell** [comment]
> If we need to jump on a call to go over it better I am all for it.

@VegasHC yes please. I have time tomorrow (Wednesday) and a little bit on Thursday, after that I'm off for the holidays.

**Comment by VegasHC** [comment]
When after the holiday are you available?

**Comment by edalzell** [comment]
> When after the holiday are you available?

Dec 27-30, in general but may be in and out doing family things. Otherwise Jan 3 onwards.

**Comment by edalzell** [comment]
What do you think of this @VegasHC?
<img width="1698" alt="CleanShot 2023-01-16 at 12 19 47@2x" src="https://user-images.githubusercontent.com/6069653/212759691-93361d51-a49f-4871-844e-bc8ae3d5a4f7.png">

**Comment by VegasHC** [comment]
I spoke to Diego and he wants to know if we can make it an image instead of just text. 

Like a 100x100 resolution image we can design and put there. Like we have for the hospice education ad.
![image](https://user-images.githubusercontent.com/98860212/213016304-057ea050-b612-4bc4-977f-dbf9317c3005.png)
It would be a lot smaller than that ad.

**Comment by edalzell** [comment]
Will it always be an image? And a square one (100x100)?

**Comment by edalzell** [comment]
How's this?

<img width="1213" alt="CleanShot 2023-01-21 at 14 52 59@2x" src="https://user-images.githubusercontent.com/6069653/213890183-70dc8927-6554-49b1-8dcd-cde8312d0f4c.png">
