### ISSUE TITLE
Contact us form

### ISSUE THREAD

**Issue by VegasHC** [VegasHC/eileen200#17]
When submitting a contact us form on the website, it sends you to a 500 | server error page.

Also being able to get the contact us form submissions via email, currently not working.

**Comment by edalzell** [comment]
@VegasHC can you please sign up for a Mailjet account: https://app.mailjet.com/signup then share the credentials with me?

**Comment by VegasHC** [comment]
Okay I signed up, email: vhcyou123@gmail.com Pass: 702Vegas!

**Comment by edalzell** [comment]
@edalzell set way to add unique form to each education page.

**Comment by edalzell** [comment]
Fixed
