### ISSUE TITLE
Create a calender/event page

### ISSUE THREAD

**Issue by VegasHC** [VegasHC/eileen200#18]
We would like to have a calendar page where we can create/put our events on.

Note: use Events addon

**Comment by edalzell** [comment]
Should use this addon (I wrote it): https://statamic.com/addons/transform/events.

@VegasHC this is likely over the 5 hours for the month. Likely closer to 10, but we'd have to chat to make sure I understand what you're looking for.

**Comment by VegasHC** [comment]
We can split this project over 2 months

**Comment by edalzell** [comment]
@edalzell check out Thryv to see if calendar can be embedded into site.

**Comment by edalzell** [comment]
Hey @VegasHC, looks like we can maybe embed a calendar: https://learn.thryv.com/hc/en-us/articles/360022094032-Add-Widgets-to-Your-Website

Want to set up a meeting to see how it works? Alternatively, you can send me your thryv credentials and I can explore.

**Comment by VegasHC** [comment]
Yeah let's set up a meeting for this. I would like to include Yvette in the meeting as well as since this is her request

**Comment by edalzell** [comment]
> Yeah let's set up a meeting for this. I would like to include Yvette in the meeting as well as since this is her request

Sure, send me an email and let me know when works.
