### ISSUE TITLE
Live banner size is smaller

### ISSUE THREAD

**Issue by VegasHC** [VegasHC/eileen200#21]
I am not sure what change you made with the banner enhancement we requested but now the picture we had before in the main page is smaller. 

![image](https://user-images.githubusercontent.com/98860212/217334981-bbc66613-788e-481f-94b3-49a39a791508.png)
This is the live version which is wrong.
it should look like how it is in the staging.
![image](https://user-images.githubusercontent.com/98860212/217335058-27fa7174-c8f7-4e56-a4b3-63831f5d097c.png)
You can see all the lights of the city and everything.

**Comment by edalzell** [comment]
Looking into this @VegasHC

**Comment by VegasHC** [comment]
Awesome, thank you!
