### ISSUE TITLE
Mobile issue

### ISSUE THREAD

**Issue by VegasHC** [VegasHC/eileen200#37]
Hi Erin,

There is an issue when people are looking at the listings on their mobile devices. The customers logo covers the contact information of the customer. I included an example
![thumbnail_image1](https://user-images.githubusercontent.com/98860212/230227184-cd58b0cc-e91c-4aca-abec-9392fbd48d85.png)

**Comment by edalzell** [comment]
ok @VegasHC take a look on staging now, fixed this. The image now slides above on smaller breakpoints

**Comment by VegasHC** [comment]
hey Erin, it looks like it stills covering the information on the left.
![vhc](https://user-images.githubusercontent.com/98860212/231224425-fc3eac9b-0ce0-47c3-aeb6-f0eb9c37600e.png)

**Comment by edalzell** [comment]
Might be a browser caching issue?

Here is it on my computer: 
<img width="573" alt="CleanShot 2023-04-11 at 17 35 12@2x" src="https://user-images.githubusercontent.com/6069653/231317617-21aff728-6ba3-46c5-8cc7-4ce105f6a23c.png">

**Comment by VegasHC** [comment]
On the staging website it looks great, but it's not on the live website. 
![live](https://user-images.githubusercontent.com/98860212/231792079-e6c5fc96-7bc0-4d62-b0ed-4f878d6fc39a.png)
![staging](https://user-images.githubusercontent.com/98860212/231792116-b2328b01-a7d4-44e1-808b-03a71f00b512.png)

**Comment by edalzell** [comment]
> On the staging website it looks great, but it's not on the live website.

Yup, I put it up on staging for your review, then when you say it's good, I deploy it to production. That gives us a chance to review and correct before pushing live.

I'll deploy this today.

**Comment by VegasHC** [comment]
Awesome! thanks a lot!

**Comment by edalzell** [comment]
Deployed in https://github.com/VegasHC/eileen200/pull/38
