### ISSUE TITLE
Flyers looking to big in the Events page

### ISSUE THREAD

**Issue by VegasHC** [VegasHC/eileen200#55]
Hi Erin,

Is there any way we can make the flyers not look so huge on the events page? you had to scroll down to much just to view each one. 
And we would like to make it easier for the customer to view.

**Comment by edalzell** [comment]
> Hi Erin,
> 
> Is there any way we can make the flyers not look so huge on the events page? you had to scroll down to much just to view each one. And we would like to make it easier for the customer to view.

What are you thinking for size @VegasHC?

**Comment by VegasHC** [comment]
Can we scale it down to 67% and see how that looks? something like this
![image](https://github.com/VegasHC/eileen200/assets/98860212/acb8886e-793f-4b67-9b0a-91c36072b2d9)

**Comment by VegasHC** [comment]
this is what it looks like now looking at the event page
![image](https://github.com/VegasHC/eileen200/assets/98860212/e8c86c15-209d-46c4-8029-5ae7de8c8170)
