### ISSUE TITLE
Add a table of contents

### ISSUE THREAD

**Issue by VegasHC** [VegasHC/eileen200#57]
Hey Erin,

We would like to add a table of content that would for like on top of the page where people can click and it would drag them down to th content they picked and in that content have like a button where it says go back to top or something so they can go back to the table of contents and click on another thing they want to see. 

is that doable?

**Comment by edalzell** [comment]
Which pages do you want this on?

And can you show a simple example?

@VegasHC

**Comment by VegasHC** [comment]
We are making a Relocating to Las Vegas Page. 

So kind of like what wikipedia has. 

On wikipedia they have it on the left side and there is a button that lets you go top. 

![image](https://github.com/VegasHC/eileen200/assets/98860212/3918c70b-3c08-49c4-b2d1-52e42887ad1d)

**Comment by edalzell** [comment]
And do you want the ToC to be automatic, like from the headings? Or do you want to create it?

Is this for those very large Education pages?

**Comment by VegasHC** [comment]
This would be used for a page we are making called Relocating to Las Vegas.

Automatic from the heading would be fantastic

**Comment by edalzell** [comment]
OK, so we can use a Bard field and this addon: https://statamic.com/addons/goldnead/toc-for-bard-and-markdown.

Let me chat with the designer to get an estimate for building this out

**Comment by VegasHC** [comment]
okay awesome thanks.

**Comment by edalzell** [comment]
hey @VegasHC, we looked at this and this would be ~5 hours of work, or one month's worth of time. Shall we get started?

**Comment by VegasHC** [comment]
Yup go ahead, thanks Erin!

**Comment by edalzell** [comment]
@VegasHC I'd like you to invite some folks to this repo, but it's a lot easier if I have that ability so I don't have to bother you. Do do that, we should convert this to an organizational account and give me permissions.

Let me know when you have some time and we'll screen share it.

If you don't have time, then please invite both krzemo@4dmind.com and karol@4dmind.com to this repo

**Comment by VegasHC** [comment]
Okay I added them as collaborators

**Comment by VegasHC** [comment]
any update on this erin?

**Comment by edalzell** [comment]
Let me check.

**Comment by edalzell** [comment]
> any update on this erin?

Will have this up on staging by Tuesday
