### ISSUE TITLE
Need to add DKIM in subdomain

### ISSUE THREAD

**Issue by VegasHC** [VegasHC/eileen200#58]
hey erin,

we are using a new CRM and they are requiring that we do this.

![image](https://github.com/VegasHC/eileen200/assets/98860212/65aed8b9-fcac-4bb3-a91c-58f4ab4389f2)
k=rsa; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCr6KMgdxxgg7oT3ulMwPJs9RXgXDrI9UWU118pHEMohl3UbL3Jwp4oxp/9N3thh/3WCJnYV134zbEVolZwqaT3JsFEq/mQ/RpW/JnOZ3rnxqJPurb2bcfJol4SDxiWVObzHX31xnANzFcXnq1/5dMK5QvW4Jh7n0fm4+4ywqiy2QIDAQAB

**Comment by edalzell** [comment]
added, it may take a few hours to be recognized:

<img width="1136" alt="CleanShot 2023-08-23 at 09 23 34@2x" src="https://github.com/VegasHC/eileen200/assets/6069653/1efb933f-8f06-4969-92e5-769b7c75b081">
