### ISSUE TITLE
Fixing thumbail

### ISSUE THREAD

**Issue by VegasHC** [VegasHC/eileen200#59]
Hi Erin,

We would like the thumbnail for the website to show our logo. 

currently it is showing what's in the image. 
![image](https://github.com/VegasHC/eileen200/assets/98860212/261f85f0-2034-42f3-8342-94a5b91055c9)

**Comment by edalzell** [comment]
@VegasHC which logo? Can you please attach a high resolution version of the one  you want?

**Comment by VegasHC** [comment]
![logo sign](https://github.com/VegasHC/eileen200/assets/98860212/e0cd2280-4648-4e5c-8a8f-8514b8054043)
we would like to use this one
