### ISSUE TITLE
Enhanced Listing Change

### ISSUE THREAD

**Issue by VegasHC** [VegasHC/eileen200#6]
Make the promotion level Enhanced listing always have them be on the top of their service category.  Currently if we make a change to any provider, it will make them go to the top no matter what promotion level they have(even if a promotion level isn't selected for them).

Also have the Enhanced listings randomized everything the page "refreshes" so it isn't set by alphabetical order.

**Comment by edalzell** [comment]
I'll look at this next week.

**Comment by edalzell** [comment]
Hey @VegasHC, took a look at this.

Turns out the results are coming from Algolia, and it works locally for me, so I suspect the Algolia set up is different? Did you folks take over that Algolia account? Or make a new one? If you made a new one, did you copy the index settings?

**Comment by VegasHC** [comment]
We did take over the Algolia account

**Comment by VegasHC** [comment]
I think I might have figured out how to fix this with Algolia, I'll have to do more testing to confirm

**Comment by edalzell** [comment]
> I think I might have figured out how to fix this with Algolia, I'll have to do more testing to confirm

Perfect @VegasHC, I've assigned it to you. If you need my help, please re-assign back to me so I get a notification.
