### ISSUE TITLE
add clickable buttons

### ISSUE THREAD

**Issue by VegasHC** [VegasHC/eileen200#66]
hey erin we want to have clickable buttons like these 
![image](https://github.com/VegasHC/Vegashealthcare.com/assets/98860212/0fc3a525-e66f-459c-af7a-adf58a437bc1)

**Comment by edalzell** [comment]
@VegasHC take a look at https://staging.vegashealthcare.com/healthcare-guide/assisted-living and you'll see 2 buttons at the bottom.

If you take a look at that entry in the CP you'll see you can pick between two colours (same red/blue used in rest of site) and an optional icon.

Let me know if that is what you're looking for.

I've added that to both the one and two column blocks.

**Comment by VegasHC** [comment]
It looks great Erin! one question, are we able to get it so when they click the button it opens it in a new tab?

**Comment by edalzell** [comment]
> It looks great Erin! one question, are we able to get it so when they click the button it opens it in a new tab?

I can make that an option on the block, sure.

**Comment by edalzell** [comment]
> It looks great Erin! one question, are we able to get it so when they click the button it opens it in a new tab?

On staging for review @VegasHC

**Comment by VegasHC** [comment]
Looks great! thanks so much!
