### ISSUE TITLE
issue with a page and forms

### ISSUE THREAD

**Issue by VegasHC** [VegasHC/eileen200#69]
hey erin, 

i made a new page and created a form for it. when it save it and publish, it gives me a 505 error.

but if i remove the form box the page works. i am not sure what is wrong. 

the page is called VHC Event Sponsorship

**Comment by edalzell** [comment]
Not sure why it's broken I can get it to show up, I chose a template.

However, it doesn't look great and the logo upload won't work.

When I built this feature it was for contact us type forms, it wasn't built to support more complicated forms like this. This will require some development to make work.

In the future, it's best to schedule these types of new features and discuss so we can figure out the best approach and make sure you can do everything you need with no issues.

**Comment by edalzell** [comment]
@VegasHC can you check out staging and try to create the VHC Events form you wanted again? I want to see if my updates helped, or if not, the example I can use to make these forms work.

Thanks

**Comment by VegasHC** [comment]
So it looks like its working but the box sizes look weird.
![image](https://github.com/VegasHC/Vegashealthcare.com/assets/98860212/eb8ecb01-7398-4b4c-92a6-35e65309ce71)

**Comment by edalzell** [comment]
ah you made them required, ya I can fix that layout. The sizes are fine, the `required` bit should be below the field.

**Comment by VegasHC** [comment]
okay cool, let me know when its fixed :)

**Comment by edalzell** [comment]
ok, there's a change going up on staging. Note that you can remove the instructions, the `* required` is automatically added if you make the field required.

**Comment by edalzell** [comment]
Now things are the correct widths, check out https://staging.vegashealthcare.com/events it's using the new forms and looks good! @VegasHC

**Comment by VegasHC** [comment]
Looks fantastic! thank you!

**Comment by edalzell** [comment]
Fixed in https://github.com/VegasHC/Vegashealthcare.com/pull/70
