### ISSUE TITLE
Add CAPTCHA to contact us

### ISSUE THREAD

**Issue by VegasHC** [VegasHC/eileen200#72]
Erin,

Can we please add CAPTCHA to the contact us form? I am getting spammed by one person submitting forms over and over. 
![image](https://github.com/VegasHC/Vegashealthcare.com/assets/98860212/2c3c0ab9-798b-4bab-8d6d-5a9c18a3a779)

**Comment by edalzell** [comment]
OK, I usually recommend Akismet, as that's less use intrusive, however it is both a paid addon (mine) and service: https://akismet.com/pricing/.

Next best option is signing up for Cloudflare (https://cloudflare.com) and using Turnstile. CF is free and would be nice for your site anyway (provides protection against DDoS attacks and other things).

Let me know how you'd like to proceed.

**Comment by edalzell** [comment]
If you take the CF route, then invite me to the account so I can get it all set up. We'll want DNS access to (current w/ GoDaddy I believe), so that we can put your site behind the Cloudflare proxy.

**Comment by VegasHC** [comment]
for the akismet, its monthly? or one time payment?

**Comment by edalzell** [comment]
> for the akismet, its monthly? or one time payment?

My addon is one time, looks like the service is $14/month. There are other options (listed above). We can chat about it if you like so you understand it all.

**Comment by VegasHC** [comment]
can we talk about it this week? i'm pretty free

**Comment by edalzell** [comment]
> can we talk about it this week? i'm pretty free

Let's do it, when works for you?

**Comment by VegasHC** [comment]
lets do tomorrow! im free whenever
