### ISSUE TITLE
Addiction & Recovery page issues

### ISSUE THREAD

**Issue by edalzell** [VegasHC/eileen200#77]
On the page Addiction and Recovery page (vegashealthcare.com/recovery) I can only see the top part of the page to make edits to the text. Once it starts listing businesses I do not see them. I need to edit them (SMAHSA Certified) should be (SAMSHA Certified). And then there is the potential to update these sites as we confirm resources, so being able to update that page is important and I want to make sure I know if I need to go through you or if I can do it and I am missing something.

**Comment by VegasHC** [comment]
Following up to see where we are on this.

**Comment by edalzell** [comment]
> Following up to see where we are on this.

I'll get this done this week.

**Comment by edalzell** [comment]
Looks like there was an error in the CP for that 1-col field, I have fixed that in production, and you can now edit the whole thing.

**Comment by VegasHC** [comment]
Thank you
