### ISSUE TITLE
Vegashealthcare.com/ Work on educational page for different catergories

### ISSUE THREAD

**Issue by VegasHC** [VegasHC/eileen200#8]
As we had discussed, the idea is to have a “Hospice Education page”. This page will a basic static page where people can come to learn about hospice. It will be linked to the add at the top of the Hospice category. When people search hospice, it should be a graphic up top saying “What is Hospice: Hospice Education”. This graphic should not have a logo and should be general information provided by Vegas Healthcare and CompassionCare Hospice.  
 
It will have a paragraph or two explaining what hospice is and general information.   

Under the paragraphs (with a picture or two next to them), we would put the videos that they produced. The videos could be hosted on YouTube(under a “Hospice education” playlist). They would be tiled individually on the site so people could click and learn. These videos will be on our site with a short description of what’s in the video. All the content needs to be provided by Compassioncare. I can schedule a call to get content from Julie. 

 
Underneath that, we could place a simple paragraph with contact form. Enter info if you have questions about hospice. That data would go to us(so we can track it), as well as CompassionCare so they can follow up and see value.  

I attached a video for visual.

https://user-images.githubusercontent.com/98860212/187547527-c49ab650-75a9-48ab-8c25-5b1302f39e3b.mp4

**Comment by edalzell** [comment]
I'll take a look at this next week.

**Comment by edalzell** [comment]
@VegasHC can you please add `jmalko@shoutmedia.net` to the repo please? He's a colleague of mine that will be helping me out on this.

**Comment by VegasHC** [comment]
> @VegasHC can you please add `jmalko@shoutmedia.net` to the repo please? He's a colleague of mine that will be helping me out on this.

How do I do this?

**Comment by edalzell** [comment]
In the settings: https://github.com/VegasHC/eileen200/settings/access.

I would do it but I don't have permissions to add people.

**Comment by VegasHC** [comment]
Okay, I sent him the invite

**Comment by VegasHC** [comment]
Any updates on this? what are we looking at for ETA?

**Comment by edalzell** [comment]
Aiming for next week.

**Comment by VegasHC** [comment]
Awesome, thank you!

**Comment by edalzell** [comment]
Looking to wrap this up mid-next week

**Comment by jmalko** [comment]
Team,

I've pushed to a new branch that incorporates Page Builder style editing.
- You now have access to adding "rows" of content with 1, 2, or 3 columns of Bard content (text and images). 
- You also have the option to add Code
- I made a special two-column row for videos

There are several options you can adjust to add background colors, images, vertical padding, and more.  Please look for the page in Collections > Pages > Hospice Education to see the layout in action.

Remainer of tasks include incorporating the page into nav, giving it some sort of special priority in search, and making adjustments based on your feedback.

https://github.com/VegasHC/eileen200/tree/8-vegashealthcarecom-work-on-educational-page-for-different-catergories

**Comment by edalzell** [comment]
@VegasHC I can't get this on staging as I don't have credentials anymore, can you please send them to me (via email)?

**Comment by VegasHC** [comment]
@edalzell Just sent them to you

**Comment by edalzell** [comment]
I have also upgraded to the latest version of Statamic and Laravel to keep you folks current.

I'll be reviewing this on Monday with Jonathan and then I can walk you through it @VegasHC to get your feedback. Page is here, for reference: https://staging.vegashealthcare.com/hospice-education

**Comment by edalzell** [comment]
@VegasHC can we have a call next week about this please? I'm a bit confused on when it should be visible.
